openapi: 3.0.0
info:
  title: Getir Project
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /getir:
    post:
      summary: Get data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate:
                  type: string
                  pattern: '^\d{4}-\d{2}-\d{2}'
                  description: Date in format YYYY-MM-DD
                endDate:
                  type: string
                  pattern: '^\d{4}-\d{2}-\d{2}'
                  description: Date in format YYYY-MM-DD
                minCount:
                  type: integer
                  description: Minimum value of sum of values in counts array
                maxCount:
                  type: integer
                  description: Maximum value of sum of values in counts array
              additionalProperties: false
              required:
                - startDate
                - endDate
                - minCount
                - maxCount
            example:
              startDate: "2016-01-26"
              endDate: "2018-02-02"
              minCount: 2500,
              maxCount: 3000
